Update

diff --git a/GoogleCloud/GEANT4_simulations/ultimate_geant4_simulation.yaml b/GoogleCloud/GEANT4_simulations/ultimate_geant4_simulation.yaml
--- a/GoogleCloud/GEANT4_simulations/ultimate_geant4_simulation.yaml
+++ b/GoogleCloud/GEANT4_simulations/ultimate_geant4_simulation.yaml
@@ -27,13 +27,21 @@ spec:
           # Authenticate with Google Cloud using the service account key
           gcloud auth activate-service-account --key-file=/secret/key.json
 
+          # Download the MyDetectorConstruction.cc
+          echo "Downloading MyDetectorConstruction_${SIMULATION_INDEX}.cc from the bucket"
+          gsutil cp gs://myg4-bucket/MyDetectorConstruction_${SIMULATION_INDEX}.cc /home/geant4lab/Geant4_projects/G4_Project/MyDetectorConstruction_${SIMULATION_INDEX}.cc || { echo "Error downloading MyDetectorConstruction_${SIMULATION_INDEX}.cc from the bucket"; exit 1; }
+
+          # Rename MyDetectorConstruction_${SIMULATION_INDEX}.cc
+          echo "Renaming MyDetectorConstruction_${SIMULATION_INDEX}.cc from the bucket"
+          mv /home/geant4lab/Geant4_projects/G4_Project/MyDetectorConstruction_${SIMULATION_INDEX}.cc /home/geant4lab/Geant4_projects/G4_Project/MyDetectorConstruction.cc || { echo "Error renaming MyDetectorConstruction_${SIMULATION_INDEX}.cc to MyDetectorConstruction.cc"; exit 1; }
+
           # Download the PrimarySpectrum.cc
           echo "Downloading PrimarySpectrum_${SIMULATION_INDEX}.cc from the bucket"
-          gsutil cp gs://myg4-bucket/PrimarySpectrum_${SIMULATION_INDEX}.cc /home/geant4lab/Geant4_projects/G4_Project/PrimarySpectrum_${SIMULATION_INDEX}.cc || { echo "Error downloading input_${SIMULATION_INDEX}.in from the bucket"; exit 1; }
+          gsutil cp gs://myg4-bucket/PrimarySpectrum_${SIMULATION_INDEX}.cc /home/geant4lab/Geant4_projects/G4_Project/PrimarySpectrum_${SIMULATION_INDEX}.cc || { echo "Error downloading PrimarySpectrum_${SIMULATION_INDEX}.cc from the bucket"; exit 1; }
 
           # Rename PrimarySpectrum_${SIMULATION_INDEX}.cc
           echo "Renaming PrimarySpectrum_${SIMULATION_INDEX}.cc from the bucket"
-          mv /home/geant4lab/Geant4_projects/G4_Project/PrimarySpectrum_${SIMULATION_INDEX}.cc /home/geant4lab/Geant4_projects/G4_Project/PrimarySpectrum.cc || { echo "Error renaming input_${SIMULATION_INDEX}.in to input.in"; exit 1; }
+          mv /home/geant4lab/Geant4_projects/G4_Project/PrimarySpectrum_${SIMULATION_INDEX}.cc /home/geant4lab/Geant4_projects/G4_Project/PrimarySpectrum.cc || { echo "Error renaming PrimarySpectrum_${SIMULATION_INDEX}.cc to PrimarySpectrum.cc"; exit 1; }
 
           # Download the input file from the bucket
           echo "Downloading input_${SIMULATION_INDEX}.in from the bucket"
@@ -71,4 +79,4 @@ spec:
       - name: gcs-key-volume
         secret:
           secretName: gcs-myg4-key
-      restartPolicy: Never      
+      restartPolicy: Never   
